### ISSUE TITLE
Allow void return types in JSPI promising exports

### ISSUE THREAD

**Issue by brendandahl** [WebAssembly/js-promise-integration#10]
In the current spec, it looks like a return result is required from an export that will be a promising function. This seems like an arbitrary requirement. It also make creating automatic wrappers of existing functions that have no return result slightly more complicated since they need to have a dummy return result.

There are some examples in:
https://bugs.chromium.org/p/v8/issues/detail?id=13231

Binaryen code that had to be added to work around this in v8:
https://github.com/WebAssembly/binaryen/blob/1ae9b7e59e17c60ee82fefb25c09cdc00100608a/src/passes/JSPI.cpp#L118-L124

**Comment by RossTate** [comment]
I didn't intend for the `result` type-list to have to be non-empty, nor can I think of a reason for it. Could you point to where you see this in the spec? (Sorry, I'm failing to find it.)

**Comment by fgmccabe** [comment]
However, there remains the issue of what kind of value to pass into any callback function attached to the promise. When you have no return values pass in undefined? When there are three return values pass in an array?

**Comment by RossTate** [comment]
Do what the existing JS API does for non-singular result lists.

**Comment by fgmccabe** [comment]
I found another WTF for JS:
console.log([1]+4)

It prints 14!
