### ISSUE TITLE
Passing a non-Suspender object to a suspending import?

### ISSUE THREAD

**Issue by thibaudmichaud** [WebAssembly/js-promise-integration#12]
With the revised "static" API, the application can pass any externref value where the suspending import expects a Suspender object. What happens if this value is not a Suspender?
I think we should specify that the wrapper checks the runtime type of the value and raises a wasm trap if it's not a Suspender. Any other suggestions?

**Comment by fgmccabe** [comment]
Agreed.

**Comment by RossTate** [comment]
Good catch. I concur as well.
