### ISSUE TITLE
Remark about using it to implement OCaml effect handlers

### ISSUE THREAD

**Issue by chambart** [WebAssembly/js-promise-integration#17]
At the last GC meeting, I was asked by @fgmccabe whether promise-integration would allow implementing OCaml effects handler.
After some reading and experiments with v8, it seems that this would be sufficient.

Note that the current v8 implementation (using node canary https://nodejs.org/download/v8-canary/v20.0.0-v8-canary202301223978c9668c/) does not seem actually sufficient. We need to be able to call functions passed from wasm to js as suspending, as in this minimal example:

```js
"use strict";

const fs = require('fs');

function sleep(time) {
    console.log("sleep");
    return(
        timers.setTimeout(time, 42).then(_ => {
            console.log('sleep finish');
            return;
        }));
}

function call_stuff(func) {
    console.log('call_stuff');
    var suspending_func = new WebAssembly.Function(
        {parameters: ['externref', 'i32'], results: ['i32']},
        func,
        {suspending:"first"}
    )
    console.log('do call_stuff');
    var _some_promise = suspending_func();
}

var suspending_sleep = new WebAssembly.Function(
    {parameters: ['externref', 'i32'], results: []},
    sleep,
    {suspending:"first"},
)

var imports = {
  from_js : {
      sleep : suspending_sleep,
      call_stuff : call_stuff,
  }
}

const wasmBuffer = fs.readFileSync('./test.wasm');

WebAssembly.instantiate(wasmBuffer, imports).then(module => {
    console.log("done");
});
```

```wast
(module
  (import "from_js" "sleep" (func $sleep (param externref) (param i32)))
  (import "from_js" "call_stuff" (func $call_stuff (param (ref func))))

  (func $cb (param $suspender externref) (result i32)
    (call $sleep (local.get $suspender) (i32.const 100))
    (i32.const 1234)
  )

  (func $start
    (call $call_stuff (ref.func $cb))
  )

  (start $start)
)
```

I might have done something stupid, but otherwise, currently the wrapping of the function in Webassembly.Function seems unimplemented:
```
#
# Fatal error in , line 0
# unimplemented code
#
```

I can retry when this is lifted, or if there are other options are available that I didn't see.

**Comment by chambart** [comment]
Well in fact being able to give back the function to javascript is not strictly necessary, the compiler can also generate a different javascript caller function for each webassembly function that can be called that way.

**Comment by fgmccabe** [comment]
I have not yet fully grokked what you are trying to do. Will obviously look at the unimplemented error.
However, your call_stuff function will never work. One of the reasons why is that we are not permitted to suspend JS functions using JSPI. So, importing something like suspending_sleep is ok, but not call_stuff.
In addition, wrapping is always a pairing operation. In addition to wrapping imports, you also need to wrap exports. This is the equivalent of the prompt delimiter.

**Comment by fgmccabe** [comment]
The reason that call_stuff will not work (ever) is precisely that you need a Suspender object; you also will not be allowed to suspend a call with JS frames.
