### ISSUE TITLE
Please implement Atomics.waitAsync as well!

### ISSUE THREAD

**Issue by tlively** [WebAssembly/js-promise-integration#20]
The stage 3 [`Atomics.waitAsync`](https://github.com/tc39/proposal-atomics-wait-async) proposal combined with JSPI will allow Emscripten to stop busy-waiting for locks, condition variables, and other blocking synchronization primitives on the main thread, which will be a great win for performance and efficiency for large, multithreaded applications. It would be great if we could assume that the presence of JSPI implied the presence of `Atomics.waitAsync` across browsers so we don't have to maintain a polyfill or continue busy waiting.

**Comment by fgmccabe** [comment]
I don't think that I would support adding an explicit dependency here. What is the implementation status of atomics?

**Comment by tlively** [comment]
This is just an informal request for implementers to consider :)

`Atomics.waitAsync` is its own TC39 proposal, and while all browsers support general `Atomics`, only blink currently supports `Atomics.waitAsync`.

**Comment by ajklein** [comment]
Some updates:
* `Atomics.waitAsync` made it to Stage 4 and is now [merged](https://tc39.es/ecma262/#sec-atomics.waitasync) into the core JS spec
* It's supported in [Safari 16.4](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes#New-Features)
* Firefox seems to be the remaining non-supporting browser ([tracking bug](https://bugs.webkit.org/show_bug.cgi?id=241414)).

@eqrion FYI as you're thinking about prioritizing JSPI work.

**Comment by fgmccabe** [comment]
Current semantics of JSPI should address this question.
