### ISSUE TITLE
Interaction between JS and Wasm

### ISSUE THREAD

**Issue by yurydelendik** [WebAssembly/js-promise-integration#26]
Maybe it is implementation specific.  Currently I'm not sure how to handle the specific test. The JS invokes `promising` function, the Wasm function invokes JS import (synchronously), JS import calls Wasm back, and finally makes a call to suspending import. The suspender is pass as a parameter in every call. See code below:

```
var suspending_fn = new WebAssembly.Function(
  {parameters:['i32'], results:['f64']},
  async (n) => { return n / 100; },
  {suspending:"first"}
);
var in_out_fn = (s) => { return ins.exports.cont(s, 42); }

var ins = wasmEvalText(`(module
    (import "js" "imp" (func $js_imp (param externref i32) (result f64)))    
    (import "js" "out" (func $js_out (param externref) (result f64)))
    (func (export "cont") (param externref i32) (result f64)
      (call $js_imp (local.get 0) (local.get 1))
    )
    (func (export "test") (param externref) (result f64)
      (call $js_out (local.get 0))
      (;call $js_imp (local.get 0) (i32.const 3);)
    )
)`, {
  "js": {
    out: in_out_fn,
    imp: suspending_fn,
  }
});

var test =  new WebAssembly.Function(
  {parameters:[], results:['f64']},
  ins.exports.test,
  {promising : "first"}
);

var res = test();
```

What will happen with stack frames of `in_out_fn` when suspending function returns a promise?

If possible, can you explain what is an implementation will do during each call? It is fine to do it in terms of V8.

**Comment by fgmccabe** [comment]
If I am reading the code correctly, this is intended to fail. The reason being that we are not permitted suspended with any JS frames on the stack.

The way it's implemented in V8 involves using a counter for calls into JS: increment when calling in JS and decrementing on return. The counter is associated with the suspender.

If the counter is non-zero when trying to suspend, that means there is at least one JS frame on the suspending stack.

Hope this helps. 

Note that V8 also switches to the central stack for all calls to JS. So, in theory, another way of implementing the check is to verify that one is not executing on the central stack when suspending.

**Comment by yurydelendik** [comment]
> this is intended to fail. The reason being that we are not permitted suspended with any JS frames on the stack.

> another way of implementing the check is to verify that one is not executing on the central stack when suspending.

It helps. It is failing in my implementation for reason being on central stack.
