### ISSUE TITLE
Add way to query whether suspender will trap?

### ISSUE THREAD

**Issue by hoodmane** [WebAssembly/js-promise-integration#29]
The spec says the following:

> The WebAssembly function returned by `WebAssembly.Function` is a function whose behavior is determined as follows:
>  ...
> 3. Traps if `suspender`'s state is not **Active**[`caller`] for some `caller`
> 4. Lets `frames` be the stack frames since `caller`
> 5. Traps if there are any frames of non-suspendable functions in `frames`

It's reasonably easy for us to manually track whether our suspender is in state **Active**[`caller`]. On the other hand, it's much harder to know if there are non-suspendable functions on the stack, especially in more complex code. We can't ask forgiveness because there is no way to recover from a trap from within wasm. It would be helpful if there were a way to ask for permission so that we could avoid the trap ahead of time.

My specific use case is as follows:
```py
pyodide.runPythonSyncifying(`
from asyncio import sleep, ensure_future
from ctypes import CFUNCTYPE, c_int

def f():
   print(1)
   ensure_future(sleep(1)).syncify()
   print(2)

# works perfectly:
f()

# Force a trampoline call through JavaScript. Fatally fails because 
# 5. Traps if there are any frames of non-suspendable functions in frames
ctypes_f = CFUNCTYPE(None)(f)
ctypes_f()
`);
```
I would like to fix it to raise a Python exception instead. You can try it out in the debug console here in a browser with JSPI enabled:
https://pyodide.org/en/stable/console.html

**Comment by fgmccabe** [comment]
I am afraid that I don't believe that it would be high priority to implement the kind of test you are asking for. However, priorities have a habit of reflecting shifting times.

**Comment by hoodmane** [comment]
> I don't believe that it would be high priority to implement the kind of test you are asking for

I have the same impression but it can't hurt to ask. My guess is that a lot of other people with complex JSPI use cases may have similar problems, so maybe once there is more user feedback in favor of it... Of course we are super excited about the JSPI even without this improvement.

It seems to me that this clearly shouldn't get an instruction but if a mechanism like [wasm builtin imports](https://github.com/WebAssembly/js-string-builtins/blob/main/proposals/js-string-builtins/Overview.md#do-we-need-a-new-import-mechanism-for-wasm-builtin-functions) is added, it shouldn't be too hard to spec a function that tests for this.

**Comment by joemarshall** [comment]
It does feel to me also that for use cases beyond the obvious uses (e.g. waiting for async fetch) there are likely to be other cases where people want to use this functionality for things where call stacks are complex and it is hard to track what is on there without instrumenting everything. Especially when the error drops you out of the wasm stack without being catchable. Especially with emscripten and binaryen stuff that mixes JavaScript and wasm I wouldn't be surprised if there are weird edge cases that we need to know about.

**Comment by sjrd** [comment]
I'd like to voice a +1 here, from the perspective of the Scala.js toolchain.

Essentially our requirement is similar to the original one: we would like to expose illegal attempts to call a `Suspending` function as catchable Scala.js exceptions, rather than traps.

Our toolchain, at least when compiled in the "debug" mode that checks everything, currently guarantees that the Wasm code it produces never traps. In any situation where a trap might occur (think null dereferencing for example), we test and throw a catchable exception instead. This is a very strong guarantee that ensures, notably, that testing frameworks can catch mistakes without crashing themselves, for example!

If we add JSPI to our language features, however, we basically have to break that guarantee!

Could we perhaps have a way to *throw* an EH exception rather than trapping? It could even be a JavaScript exception, which would make sense to me, since we are talking to a JavaScript API after all.

Perhaps this should even be the default way to report failures here? If not, maybe an `options` argument to `new WebAssembly.Suspending` would allow us to configure the failure mode?
```js
"myImport": new WebAssembly.Suspending(fun, { failureMode: 'exception' }),
```
?

**Comment by hoodmane** [comment]
@sjrd one thing that helps a little bit is that with the new `catch_all_ref` it's now possible to do:
```wat
try
    call $suspending_func
catch_all_ref
    call $update_error
    throw_ref
end
```
and then `$update_error` can be a JS function that inspects the error to see if it's a `can't suspend through JS Frames` trap and if so convert it into an exception that your other code knows how to handle. If you do this consistently whenever you call a suspending function, then there's no risk that the error actually came from further down the stack. 

This is an imperfect solution because if you call into other peoples' code and they trigger this trap, the error may be unrecoverable and we are at risk of continuing on with a corrupted runtime. Maybe by inspecting the stack in the error, we can confirm that the current frame is the bottom-most in the error's stack.

**Comment by sjrd** [comment]
Even `catch_all_ref` cannot catch `trap`s. I just tested on Chrome. The engines enforce this with a dedicated exception for trap exceptions, so that Wasm can never catch them.

**Comment by rossberg** [comment]
Right, traps are unrelated to exceptions (even though they are converted to JS exceptions on the outside, when Wasm is embedded in JS). They are fatal program failures that abruptly terminate Wasm execution.

**Comment by fgmccabe** [comment]
There is an agenda item in the 11/04/24 meeting of the stacks subgroup that refers to this issue.

**Comment by sjrd** [comment]
Are we allowed to join that meeting, or do we have to specifically be part of the stacks subgroup to do so? I found a Zoom link publicly available on the meetings repo, but that seems like a poor excuse to just barge in without asking.

**Comment by fgmccabe** [comment]
The primary requirement is that you are a member of the CG. However, we often have visitors; so you can join as a visitor (if you are not a member of the CG).

**Comment by sjrd** [comment]
I'm a member of the CG, even if I rarely join the meetings. I'll attend this one, then. Thank you.

**Comment by fgmccabe** [comment]
A follow up: it seems that all other WebAssembly.RuntimeErrors represent non-recoverable situations (i.e., traps). I also do not feel that issuing a JavaScript TypeError is appropriate for this situation.
So, going forward: either we have the first recoverable RuntimeError or go with the original request here: of adding a predicate (e.g., IsSafeToSuspend). Personally, I don't like either solution.
In the longer term, I believe that it is entirely possible that the wasm community may adopt a mechanism for recovering from traps (e.g., to allow test runners to work properly). But, there is no guarantee about that.

Thoughts?

**Comment by eqrion** [comment]
> A follow up: it seems that all other WebAssembly.RuntimeErrors represent non-recoverable situations (i.e., traps). I also do not feel that issuing a JavaScript TypeError is appropriate for this situation. So, going forward: either we have the first recoverable RuntimeError or go with the original request here: of adding a predicate (e.g., IsSafeToSuspend). Personally, I don't like either solution. In the longer term, I believe that it is entirely possible that the wasm community may adopt a mechanism for recovering from traps (e.g., to allow test runners to work properly). But, there is no guarantee about that.
> 
> Thoughts?

How about adding a WebAssembly.SuspendError class here [1]?

[1] https://webassembly.github.io/spec/js-api/index.html#error-objects

**Comment by fgmccabe** [comment]
It is still a 'first'. But, better than using RuntimeError.

**Comment by hoodmane** [comment]
I still think the `IsSafeToSuspend` query would be cleanest to use because with a try/catch chance of catching a failed suspend further down the stack. But I'm happy to see any fix =)

**Comment by fgmccabe** [comment]
Have landed change to spec (&V8): we throw a SuspendError instead of trapping.

**Comment by hoodmane** [comment]
@sjrd @fgmccabe I'm trying to use this to actually catch a suspend error and having trouble. First I thought there would be a tag I could import that would let me catch these with `catch $tag` but `WebAssembly.SuspendError` is not a tag. So then I thought that `catch_all_ref` would work fine, so I tried this:
```wat
(module
  (import "env" "suspend" (func $suspend (result i32)))
  (import "env" "fallback" (func $fallback (result i32)))
  (import "env" "isSuspendError" (func $isSuspendError (param exnref) (result i32)))

  (func (export "f") (param i32) (result i32) (local exnref)
    (block $h (result exnref)
      (try_table (result i32) (catch_all_ref $h)
        call $suspend
      )
      ;; If suspend succeded return result
      (return)
    )
    ;; Inspect the error we've caught for whether it is a SuspendError
    (local.tee 1)
    (call $isSuspendError)
    ;; if it's a SuspendError, use fallback instead
    (if (then
        call $fallback
        return
    ))
    ;; Otherwise rethrow error
    (local.get 1)
    (throw_ref)
  )
)
```
But the call to `isSuspendError` fails with `TypeError: type incompatibility when transforming from/to JS`. I tried using `ref.cast anyref` and then `extern.convert_any` to convert the `exnref` to an `externref` which would be able to cross the JS boundary, but that fails validation for reasons that I don't understand. @sjrd have you successfully used this API to catch and filter out `SuspendError`s? How can I do it?

**Comment by sjrd** [comment]
`SuspendError`s are JavaScript exceptions. You need to use the `WebAssembly.JSTag` to catch JS exceptions as `externref`s, then call your `$isSuspendError` with that `externref` as an argument.

(written by hand for illustration; expect lots of small mistakes)
```wat
(module
  ...
  (import "env" "JSTag" (tag $jsTag (param externref)))
  (import "env" "isSuspendError" (func $isSuspendError (param externref) (result i32)))

  (func (export "f") (param i32) (result i32) (local exnref)
    (block $h (result externref) (result exnref)
      (try_table (result i32) (catch_ref $jsTag $h)
        call $suspend
      )
      ;; If suspend succeded return result
      (return)
    )
    (local.set 1)
    ;; Inspect the error we've caught (the externref still on the stack) for whether it is a SuspendError
    (call $isSuspendError)
    ;; if it's a SuspendError, use fallback instead
    (if (then
        call $fallback
        return
    ))
    ;; Otherwise rethrow error
    (local.get 1)
    (throw_ref)
  )
)
```

> I tried using `ref.cast anyref` and then `extern.convert_any` to convert the `exnref` to an `externref` which would be able to cross the JS boundary, but that fails validation for reasons that I don't understand.

`exnref` lives in a completely separate world from `externref`s and `anyref`s. It cannot be converted to/from them, and cannot be passed to JS code. The only thing you can do with an `exnref` is store it within Wasm, and eventually call it with `throw_ref`.

**Comment by hoodmane** [comment]
Thanks for the help @sjrd!

**Comment by hoodmane** [comment]
Hmm it seems that it first executes the function and _then_ raises the `SuspendError`. I was hoping it would raise the `SuspendError` before executing the body of the function. This seems rather problematic. I guess that means we have to implement a `canSuspend` by calling a suspending function with a no-op body? But it seems a lot more expensive than calling a function that directly queries the runtime for whether we can suspend or not.

**Comment by sjrd** [comment]
Hum ... That might not be according to spec:
https://webassembly.github.io/js-promise-integration/js-api/#create-a-suspending-function
Throwing the `SuspendError` should happen before calling the function, IIUC.

**Comment by hoodmane** [comment]
Sure sounds like it:

> 5. If the entry for async_context in map is not active, then:
>    1. Perform throw a JavaScript exception with a SuspendError exception.
> 6. Prepare to run script with relevant settings.

I'll open a bug report against v8.

**Comment by hoodmane** [comment]
Test case:
```wat
(module
  (import "e" "s" (func $suspend))
  (func (export "f")
    call $suspend
  )
)
```

```js
let x = 0;
const code = new Uint8Array([
  0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x04, 0x01, 0x60, 0x00,
  0x00, 0x02, 0x07, 0x01, 0x01, 0x65, 0x01, 0x73, 0x00, 0x00, 0x03, 0x02, 0x01,
  0x00, 0x07, 0x05, 0x01, 0x01, 0x66, 0x00, 0x01, 0x0a, 0x06, 0x01, 0x04, 0x00,
  0x10, 0x00, 0x0b, 0x00, 0x11, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x01, 0x0a, 0x01,
  0x00, 0x07, 0x73, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64,
]);
const mod = new WebAssembly.Instance(new WebAssembly.Module(code), {
  e: {
    s: new WebAssembly.Suspending(async () => {
      x = 1;
    }),
  },
});

try {
  console.log(mod.exports.f());
} catch (e) {
  console.log(e.name); // logs SuspendError
}
console.log(x); // Should log 0, actually logs 1.
```

**Comment by hoodmane** [comment]
Opened a v8 PR:
https://chromium-review.googlesource.com/c/v8/v8/+/6800062

**Comment by hoodmane** [comment]
And it is merged now. So now this works correctly on the main branch.
