### ISSUE TITLE
Removing Suspender from overview?

### ISSUE THREAD

**Issue by bakkot** [WebAssembly/js-promise-integration#31]
[This comment](https://github.com/WebAssembly/js-promise-integration/issues/2#issuecomment-1915536180) says Suspender is being removed, but it's still present in [the overview](https://github.com/WebAssembly/js-promise-integration/blob/main/proposals/js-promise-integration/Overview.md). Seems like the overview ought to updated?

**Comment by fgmccabe** [comment]
This is correct. The overview is being updated; a proposed update is available at #30.

**Comment by bakkot** [comment]
Ah, excellent. Sorry for not checking PRs first.
