### ISSUE TITLE
Simpler way of getting async exports?

### ISSUE THREAD

**Issue by bakkot** [WebAssembly/js-promise-integration#33]
The new explainer (as of #30) is much simpler than before, which I greatly appreciate.

But it's still kind of awkward, especially with regards to exports: the user has to manually wrap every async export with `WebAssembly.promising`, after the fact. If you have a bunch of async exports, that's annoying.

It would be nice if this could be avoided. For example, you could say that any instance which has at least one `Suspending` import automatically has an `asyncExports` property with the same properties as the regular `exports`, except that they'd be wrapped in `WebAssembly.promising`. This could be done lazily rather than actually needing to create all those extra functions.

```js
var importObj = {js: {
  init_state: init_state,
  compute_delta: new WebAssembly.Suspending(compute_delta),
}};

var sampleModule = new WebAssembly.Instance(demoBuffer, importObj);

await sampleModule.asyncExports.update_state();
// equivalent to `await WebAssembly.promising(sampleModule.exports.update_state)()`
```
And then you could get rid of `WebAssembly.promising` entirely.

**Comment by fgmccabe** [comment]
This is an interesting idea.

**Comment by fgmccabe** [comment]
A small follow-up: we tried (and failed) to avoid modifying the API for WebAssembly.instantiate. In part because of WebAssembly.Function (which is part of the js-types proposal).
In particular, exposing something like asyncExports would make the WebAssembly.Function story significantly harder.

**Comment by bakkot** [comment]
How so? Both the regular exports and the async ones could still be `WebAssembly.Function`s, just with different types. Which I assume would be the plan for regular exports vs `promising` ones.

Indeed this proposal could be done in userland, though it's awkward:

```js
let seen = new Map;
sampleModule.asyncExports = new Proxy({}, {
  get(target, prop) {
    if (!seen.has(prop)) {
      seen.set(prop, WebAssembly.promising(sampleModule.exports[prop]));
    }
    return seen.get(prop);
  },
  // other traps elided for brevity
});
```

**Comment by fgmccabe** [comment]
This is not what I meant. (Note that WebAssembly.Function is not yet standardized).
The 'story' for WebAssembly.Function is that it is equivalent to a singleton WebAssembly module; however, that would no longer be possible as you would need to export two functions from WebAssembly.Function: one that is promising, and one that isnt.

**Comment by bakkot** [comment]
Hm, ok, I'm missing some context; this is the first I'm hearing of that story. I'll leave this as a suggestion for consideration by people who have more context, then.

**Comment by fgmccabe** [comment]
At the moment, there is no plan to extend WebAssembly.promising to access tables directly.

**Comment by fgmccabe** [comment]
However, WebAssembly.promising is agnostic as to where it gets its function arguments from.

**Comment by yurydelendik** [comment]
> At the moment, there is no plan to extend WebAssembly.promising to access tables directly.

> However, WebAssembly.promising is agnostic as to where it gets its function arguments from.

That's correct. I'm just trying to understand the "get rid of WebAssembly.promising entirely" claim. If we are not removing `WebAssembly.promising`, having several ways to do the same operation can be problematic. The `asyncExports` just provides a shortcut for exported functions that can be achieved by more generic operation.

**Comment by fgmccabe** [comment]
Interesting idea but, in the end, not actionable at the moment.
