### ISSUE TITLE
Is WebAssembly.promising result a Wasm function?

### ISSUE THREAD

**Issue by yurydelendik** [WebAssembly/js-promise-integration#51]
Per overview, it is a JS function. The test at https://github.com/WebAssembly/js-promise-integration/pull/47/files#diff-57f65c4de989ee6428f54af7ab1d139ca303e4cfca46b582bd8dfc4086b0b589R392 further asserts that it can be a `WebAssembly.Function`. In SM implementation it is a native function.

Is it a requirement that the result of `WebAssembly.promising` call must be a `WebAssembly.Function`?

**Comment by fgmccabe** [comment]
A quick response:
1. The result of WebAssembly.promising is a JavaScript function, not a WebAssembly.Function. If the explainer says differently, I will amend it.
2. The argument of WebAssembly.promising *must* be a WebAssembly.Function (e.g. as exported from a module).

The rationale is to avoid, by construction, the so-called sandwich scenario where it becomes ambiguous as to which call is suspended in the case of an import returning a Promise: it is always the innermost call to a WebAssembly.promising function.

**Comment by yurydelendik** [comment]
The test was fixed by #52.

Closing this issue as answered.
