### ISSUE TITLE
Idea: alternative to suspender, blunt async option

### ISSUE THREAD

**Issue by Pyrolistical** [WebAssembly/js-promise-integration#6]
How about instead of suspender, we add an option to enable all import/export async.

Using the example in the overview,
```js
var init_state = () => 2.71;
var importObj = {js: {
    init_state: init_state,
    compute_delta: () => fetch('data.txt').then(res => res.text()).then(txt => parseFloat(txt))
}};

fetch('demo.wasm').then(response =>
    response.arrayBuffer()
).then(buffer =>
    WebAssembly.instantiate(buffer, importObj, {async: true})
).then(({module, instance}) => {
    var get_state = instance.exports.get_state;
    return instance.exports.update_state();
).then((updated_value) => {
    ...
});
```

Note:
1. new `{async: true}` object in `WebAssembly.instantiate`
2. importObj functions are now allowed to be async
3. All export functions now return promises

The wasm code itself does not require any modification. Since all export functions are now async, the wasm runtime that calls back out to import functions can now resolve the returned promise.

This does add cost to **every** import/export function, but makes the api far simpler.

This is also easier to polyfill as it simply wraps all import/export functions on the js side.

**Comment by fgmccabe** [comment]
We are considering something like this. However,
a. Changing the module instantiation API is pretty heavyweight IMO, given all the dependencies folk have on it.
b. You would need to be able to mark individual functions async. Not all imports/exports should be handled in an async way.

**Comment by fgmccabe** [comment]
Closing, the API change (as noted in #30) no longer has explicit suspenders.
