### ISSUE TITLE
How is this going to work with ESM integration?

### ISSUE THREAD

**Issue by Pyrolistical** [WebAssembly/js-promise-integration#7]
Is the answer, it just simply won't, and anybody who wishes to use promises must manually call WebAssembly.instantiate?

https://github.com/WebAssembly/esm-integration

**Comment by Pyrolistical** [comment]
Ask the question the other way around https://github.com/WebAssembly/esm-integration/issues/64

**Comment by fgmccabe** [comment]
It is probably better to have this questions answered on the esm-integration repo. However, JS-Promise integration will very likely not change the API for instantiating modules (the most basic reason being that instantiation of modules is not the only gateway to passing functions into a wasm module).
